version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: rakesh
      POSTGRES_PASSWORD: ranjan
      POSTGRES_DB: user
    volumes:
      - dbvolume:/usr/postgresql/newdata
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080

  backend:
    image:  ranrakes/endgame:v1
    environment:
      DB_USER: rakesh
      DB_PASS: example
      DB: endgame
      DB_HOST: db
    links:
      - db
volumes:
  dbvolume: 
